import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { requireUser } from '@/lib/auth';
import { extractVisit, recallPriority } from '@/lib/recallLogic';
import { updateStore, newId, nowIso } from '@/lib/localDb';
import { writeAudit } from '@/lib/audit';
import { useTableStorage, processVisitUpload } from '@/lib/tableDb';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
function asArray(value: any): any[] { return Array.isArray(value) ? value : []; }
function cleanString(value: any) { return String(value || '').trim(); }
function laterOrEqual(a: any, b: any) { const left = String(a || ''); const right = String(b || ''); if (!left) return false; if (!right) return true; return left >= right; }
function uniqueSorted(values: any[]) { return Array.from(new Set(values.filter((v) => v !== null && v !== undefined && String(v).trim() !== '').map((v) => String(v).trim()))).sort(); }
function ensurePatientShape(existing: any, phone: string, firstVisit: any) { const allNames = uniqueSorted([...(asArray(existing.all_names)), existing.display_name].filter(Boolean)); const originalPhones = uniqueSorted(asArray(existing.original_phones)); const yearsVisited = uniqueSorted(asArray(existing.years_visited)).map((y) => Number(y)).filter((y) => !Number.isNaN(y)).sort((a, b) => a - b); const nameKeys = uniqueSorted([...(asArray(existing.patient_name_keys)), existing.patient_name_key].filter(Boolean)); return { id: existing.id || newId('patient_'), standard_phone: existing.standard_phone || phone, display_name: existing.display_name || 'Unknown patient', patient_name_key: existing.patient_name_key || '', patient_name_keys: nameKeys, all_names: allNames, original_phones: originalPhones, first_visit_date: existing.first_visit_date || firstVisit || null, last_visit_date: existing.last_visit_date || firstVisit || null, visit_count: Number(existing.visit_count || 0), years_visited: yearsVisited, last_doctor: existing.last_doctor || '', last_company: existing.last_company || '', duplicate_risk_level: existing.duplicate_risk_level || 'low', duplicate_risk_notes: existing.duplicate_risk_notes || '', recall_priority: existing.recall_priority || recallPriority(existing.last_visit_date || firstVisit), assignment_status: existing.assignment_status || (existing.assigned_to ? 'assigned' : 'unassigned'), assigned_to: existing.assigned_to || null, do_not_call: Boolean(existing.do_not_call), updated_at: nowIso() }; }
function mergeVisitIntoPatient(existing: any, visit: any) { const phone = visit.standard_phone; const patient = ensurePatientShape(existing || {}, phone, visit.visit_date); const name = cleanString(visit.patient_name); const nameKey = cleanString(visit.patient_name_key); const originalPhone = cleanString(visit.original_phone); const year = Number(visit.visit_year || 0); if (name) { patient.all_names = uniqueSorted([...asArray(patient.all_names), name]); if (!patient.display_name || patient.display_name === 'Unknown patient') patient.display_name = name; } if (nameKey) { patient.patient_name_keys = uniqueSorted([...asArray(patient.patient_name_keys), nameKey]); if (!patient.patient_name_key) patient.patient_name_key = nameKey; } if (originalPhone) patient.original_phones = uniqueSorted([...asArray(patient.original_phones), originalPhone]); if (year && !Number.isNaN(year)) patient.years_visited = uniqueSorted([...asArray(patient.years_visited), year]).map((y) => Number(y)).sort((a, b) => a - b); const visitDate = cleanString(visit.visit_date); if (visitDate) { if (!patient.first_visit_date || visitDate < String(patient.first_visit_date)) patient.first_visit_date = visitDate; if (laterOrEqual(visitDate, patient.last_visit_date)) { patient.last_visit_date = visitDate; if (cleanString(visit.doctor)) patient.last_doctor = cleanString(visit.doctor); if (cleanString(visit.company)) patient.last_company = cleanString(visit.company); } } patient.visit_count = Number(patient.visit_count || 0) + 1; patient.recall_priority = recallPriority(patient.last_visit_date); patient.updated_at = nowIso(); return patient; }
function conciseErrorMessage(error: any) { const msg = String(error?.message || error || 'Upload failed'); return msg.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').slice(0, 700); }

export async function POST(req: Request) {
  try {
    const user = await requireUser(['admin','manager']);
    const form = await req.formData();
    const files = form.getAll('files') as File[];
    if (!files.length) return NextResponse.json({ error: 'Upload at least one Excel file' }, { status: 400 });
    const visitCandidates: any[] = []; let rawRowCount = 0; let invalidPhoneCount = 0;
    for (const file of files) { const buffer = Buffer.from(await file.arrayBuffer()); const wb = XLSX.read(buffer, { type: 'buffer', cellDates: true }); for (const sheetName of wb.SheetNames) { const rows = XLSX.utils.sheet_to_json<Record<string, any>>(wb.Sheets[sheetName], { defval: '' }); rows.forEach((row, idx) => { rawRowCount += 1; const parsed = extractVisit(row, file.name, sheetName, idx + 2); if (!parsed.standard_phone) { invalidPhoneCount += 1; return; } visitCandidates.push({ visit_hash: parsed.visit_hash, source_file_name: parsed.source_file_name, source_sheet_name: parsed.source_sheet_name, raw_row_number: parsed.raw_row_number, patient_name: parsed.patient_name, patient_name_key: parsed.patient_name_key, original_phone: parsed.original_phone, standard_phone: parsed.standard_phone, visit_date: parsed.visit_date, visit_year: parsed.visit_year, doctor: parsed.doctor, company: parsed.company, visit_status: parsed.visit_status, created_at: nowIso() }); }); } }
    if (useTableStorage()) { const result = await processVisitUpload(user, files, visitCandidates, rawRowCount, invalidPhoneCount, files.map(f => f.name).join(', ')); await writeAudit(user.id, 'UPLOAD_VISIT_EXPORTS', 'upload_batch', result.batch.id, { files: files.map(f => f.name), rawRowCount }); return NextResponse.json(result); }
    const batchId = newId('batch_'); const createdAt = nowIso(); const batch: any = { id: batchId, filename_summary: files.map((f) => f.name).join(', '), uploaded_by: user.id, raw_row_count: rawRowCount, unique_visit_count: 0, clean_patient_count: 0, duplicate_row_count: 0, notes: '', storage_mode: 'operational_clean_recall_dataset', created_at: createdAt };
    const result = await updateStore(store => { const oldHashes = new Set<string>([...asArray((store as any).visit_hashes), ...asArray(store.unique_visits).map((v: any) => String(v.visit_hash || '')).filter(Boolean)]); store.raw_visits = []; store.unique_visits = []; (store as any).visit_hashes = Array.from(oldHashes); const patientsByPhone = new Map<string, any>(); for (const existing of asArray(store.patient_master)) if (existing.standard_phone) patientsByPhone.set(existing.standard_phone, ensurePatientShape(existing, existing.standard_phone, existing.first_visit_date)); let uniqueVisitCount = 0; let duplicateCount = 0; for (const visit of visitCandidates) { if (oldHashes.has(visit.visit_hash)) { duplicateCount += 1; continue; } oldHashes.add(visit.visit_hash); uniqueVisitCount += 1; patientsByPhone.set(visit.standard_phone, mergeVisitIntoPatient(patientsByPhone.get(visit.standard_phone), visit)); } store.patient_master = Array.from(patientsByPhone.values()); (store as any).visit_hashes = Array.from(oldHashes); batch.unique_visit_count = uniqueVisitCount; batch.clean_patient_count = store.patient_master.length; batch.duplicate_row_count = duplicateCount; store.upload_batches.push(batch); return { batch }; });
    await writeAudit(user.id, 'UPLOAD_VISIT_EXPORTS', 'upload_batch', result.batch.id, { files: files.map(f => f.name), rawRowCount }); return NextResponse.json(result);
  } catch (error: any) { return NextResponse.json({ error: conciseErrorMessage(error) }, { status: 500 }); }
}
