import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/auth';
import { useTableStorage, clearStaffCalls as clearTableStaffCalls } from '@/lib/tableDb';
import { updateStoreFresh, nowIso } from '@/lib/localDb';
import { writeAudit } from '@/lib/audit';

function recomputePatientStatus(store: any, patientId: string) { const patient = store.patient_master.find((p: any) => p.id === patientId); if (!patient) return; const latest = [...store.call_attempts].filter((c: any) => c.patient_id === patientId).sort((a: any, b: any) => String(b.attempt_at || b.created_at || '').localeCompare(String(a.attempt_at || a.created_at || '')))[0]; patient.assignment_status = latest ? (latest.booking_made ? 'booked' : latest.next_action_date || latest.next_action ? 'follow_up' : 'called') : (patient.assigned_to ? 'assigned' : 'unassigned'); patient.updated_at = nowIso(); }
export async function POST(req: Request) {
  try {
    const user = await requireUser(['admin','manager']); const body = await req.json(); const staffId = String(body.staffId || '').trim(); const confirmText = String(body.confirmText || '').trim().toUpperCase();
    const result = useTableStorage() ? await clearTableStaffCalls(user, staffId, confirmText) : await updateStoreFresh(store => { if (!staffId) throw new Error('Select a staff member whose call logs should be cleared.'); if (confirmText !== 'CLEAR') throw new Error('Type CLEAR to confirm call log cleanup.'); const staff = store.app_users.find((u: any) => u.id === staffId); if (!staff) throw new Error('Staff user not found'); const callsToRemove = store.call_attempts.filter((c: any) => c.staff_id === staffId); const callIds = new Set(callsToRemove.map((c: any) => c.id)); const affectedPatientIds = new Set(callsToRemove.map((c: any) => c.patient_id)); const bookingCount = store.bookings.filter((b: any) => b.staff_id === staffId || callIds.has(b.call_attempt_id)).length; store.call_attempts = store.call_attempts.filter((c: any) => c.staff_id !== staffId); store.bookings = store.bookings.filter((b: any) => b.staff_id !== staffId && !callIds.has(b.call_attempt_id)); affectedPatientIds.forEach((patientId: string) => recomputePatientStatus(store, patientId)); return { staff: { id: staff.id, name: staff.name, email: staff.email }, removedCalls: callsToRemove.length, removedBookings: bookingCount, affectedPatients: affectedPatientIds.size, closedFlags: 0 }; });
    await writeAudit(user.id, 'CLEAR_STAFF_CALL_LOGS', 'call_attempt', staffId, result); return NextResponse.json(result);
  } catch (error: any) { const status = error.message === 'UNAUTHENTICATED' ? 401 : error.message === 'FORBIDDEN' ? 403 : error.message === 'Staff user not found' ? 404 : 400; return NextResponse.json({ error: error.message || 'Failed to clear staff call logs' }, { status }); }
}
